variables:
  acrServiceConn: "pipeline"
  acrRepo: "demo-service"
  tag: "$(Build.BuildId)"

pool:
  vmImage: ubuntu-latest
steps:
# 第一步：构建镜像，支持自定义arguments
- task: Docker@2
  displayName: Build image
  inputs:
    command: build
    repository: $(acrRepo)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: $(tag)
    arguments: --progress plain # 自定义构建参数生效

# 第二步：推送镜像到ACR
- task: Docker@2
  displayName: Push image to ACR
  inputs:
    command: push
    containerRegistry: $(acrServiceConn)
    repository: $(acrRepo)
    tags: $(tag)