variables:
  acrServiceConn: "pipeline"
  acrRepo: "backend-test"
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest
steps:
# 1. 构建（自动带上ACR完整域名前缀）
- task: Docker@2
  displayName: Build Image
  inputs:
    command: build
    containerRegistry: $(acrServiceConn)
    repository: $(acrRepo)
    dockerfile: Dockerfile
    tags: $(tag)
    arguments: --progress plain # build模式支持arguments

# 2. 推送（直接复用构建好的完整标签）
- task: Docker@2
  displayName: Push to ACR
  inputs:
    command: push
    containerRegistry: $(acrServiceConn)
    repository: $(acrRepo)
    tags: $(tag)